### ISSUE TITLE
Grant permission for us, to allow us continue rework Leobbs 

### ISSUE THREAD

**Issue by netroby** [leobbs/leobbs#1]
Rebuild leobbs

**Comment by netroby** [comment]
@easunlee

**Comment by easunlee** [comment]
@netroby 
hi, u can contact email [htc@17do.com ( Shining Hu)].

**Comment by netroby** [comment]
Thanks for your reply,
Appreciate your time.
----------------------------
Netroby


Easun <notifications@github.com> 於 2018年9月6日 週四 下午4:56寫道：

**Comment by netroby** [comment]
@easunlee Welcome tell me your thought and advice. I would like to listen ,and then decide how to continue improve the leobbs development
