### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by benharvie** [leobbs/leobbs#29]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@christynorl) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by cnmade** [comment]
ok, thanks for reporting . just describe your found. very happy to see it

**Comment by Christynorl** [comment]
hi,@cnmade👋
Please visit this link to check it.[link](https://huntr.dev/bounties/e746f515-160f-48fe-b4a3-ad0dc53ea7be/).
thank you for read my report.

**Comment by cnmade** [comment]
now we totally removed markdown support, and it will not affect by the xss parse.

**Comment by Christynorl** [comment]
Hi,@cnmade👋
Could you please verify my report by this link [link](https://huntr.dev/bounties/e746f515-160f-48fe-b4a3-ad0dc53ea7be/).This is very helpful for me to test my tools. Thanks a lot.

**Comment by cnmade** [comment]
confirm that ,and thanks

**Comment by cnmade** [comment]
close as it stale
